[ftp]
# Reemplaza con la dirección del servidor FTP
host = 186.4.157.147
# Reemplaza con el puerto correcto 6322  
port = 6322
# Reemplaza con tu nombre de usuario FTP
user = vteksoftfinadm
# Reemplaza con tu contraseña FTP
password = svrftp.1234
# Reemplaza con la ruta remota en el servidor FTP
ruta_remota = /FINDIA
ruta_remota_Semanal = /SEMANAL
[directorio]
# Reemplaza con la ruta local en tu disco duro
ruta_local = C:\!Vtek\Respaldar
ruta_local_Semanal = C:\!Vtek\Respaldar\Semanal